### PR TITLE
GERONIMO-6658 - application/json doesn't return correct payload

### PR DESCRIPTION
**Pull request by ivanjunckes**
This is WIP as the TCK on TomEE is broken. So I can't be sure if the PR is a 100% ok.

Also I will write a test to make sure it works.

### CODE REVIEW

**Comment by rmannibucau** [comment]
If it helps singleEntry was supposed handling it properly

**Comment by ivanjunckes** [comment]
@rmannibucau it doesn't handle it properly. Gauge needs to go through map() method to get the gauge value. singleEntry prepares it for the prometheus format but doesn't work for json.

**Comment by rmannibucau** [comment]
Point was more the null check can is already done later so a map(this::map) is likely a better fix and would work for other usages and not only this one

**Comment by ivanjunckes** [comment]
I am not sure I get your reply @rmannibucau, I added some tests. Can you review them?

Also, if you have an example of this::map would be better, because I didn't get what you mean.

**Comment by rmannibucau** [comment]
If you look the code of singleEntry (what you changed) you will see it just misses a map on the metric otherwise it is exactly the same so idea was to fix singleEntry instead of duplicating the code

Side note: please dont add a test module and write the test in common module - not even need a server or endpoint ;).

If still unclear and you are ok i am also fine to just do it tomorrow, it shouldnt be more than 15mn so sure i can do it for you too.

**Comment by ivanjunckes** [comment]
I will have a look tomorrow, no need to do it for me.

**Comment by ivanjunckes** [comment]
I actually now get it, but adding map there doesn't work:

return ofNullable(metricRegistry.getMetrics().get(name))
                .map(metric -> singletonMap(name, map(metric)))
                .orElseGet(Collections::emptyMap);

It will change the return type from Metric to Object and won't work for other methods that are using it.

**Comment by ivanjunckes** [comment]
When you say a server or an endpoint are not necessary, how would you do it?

**Comment by rmannibucau** [comment]
> It will change the return type from Metric to Object and won't work for other methods that are using it.

I'm pretty confident we can make it work, worse case we add a toggle in map method but all endpoints should return the same representation

> When you say a server or an endpoint are not necessary, how would you do it?

a plain new of the endpoint then you have setters and can call endpoint to check the returned model, no need to go through serialization here

**Comment by rmannibucau** [comment]
To be concrete, here is the proposal:


    diff --git a/geronimo-metrics-common/src/main/java/org/apache/geronimo/microprofile/metrics/common/jaxrs/MetricsEndpoints.java b/geronimo-metrics-common/src/main/java/org/apache/geronimo/microprofile/metrics/common/jaxrs/MetricsEndpoints.java
    index 4293fd5..405cd45 100644
    --- a/geronimo-metrics-common/src/main/java/org/apache/geronimo/microprofile/metrics/common/jaxrs/MetricsEndpoints.java
    +++ b/geronimo-metrics-common/src/main/java/org/apache/geronimo/microprofile/metrics/common/jaxrs/MetricsEndpoints.java
    @@ -19,11 +19,13 @@ package org.apache.geronimo.microprofile.metrics.common.jaxrs;
     import static java.util.Collections.emptyMap;
     import static java.util.Collections.singletonMap;
     import static java.util.Optional.ofNullable;
    +import static java.util.function.Function.identity;
     import static java.util.stream.Collectors.joining;
     import static java.util.stream.Collectors.toMap;
     
     import java.util.Collections;
     import java.util.Map;
    +import java.util.function.Function;
     import java.util.stream.Stream;
     
     import javax.ws.rs.GET;
    @@ -133,7 +135,7 @@ public class MetricsEndpoints {
                               @Context final SecurityContext securityContext,
                               @Context final UriInfo uriInfo) {
             securityValidator.checkSecurity(securityContext, uriInfo);
    -        return singleEntry(name, findRegistry(registry));
    +        return singleEntry(name, findRegistry(registry), this::map);
         }
     
         @GET
    @@ -147,7 +149,7 @@ public class MetricsEndpoints {
             final MetricRegistry metricRegistry = findRegistry(registry);
             return prometheus.toText(
                     metricRegistry, registry,
    -                singleEntry(name, metricRegistry))
    +                singleEntry(name, metricRegistry, identity()))
                     .toString();
         }
     
    @@ -175,9 +177,10 @@ public class MetricsEndpoints {
                     .collect(toMap(Map.Entry::getKey, e -> mapMeta(e.getValue())));
         }
     
    -    private Map<String, Metric> singleEntry(final String name, final MetricRegistry metricRegistry) {
    +    private <T> Map<String, T> singleEntry(final String name, final MetricRegistry metricRegistry,
    +                                            final Function<Metric, T> metricMapper) {
             return ofNullable(metricRegistry.getMetrics().get(name))
    -                .map(metric -> singletonMap(name, metric))
    +                .map(metric -> singletonMap(name, metricMapper.apply(metric)))
                     .orElseGet(Collections::emptyMap);
         }

And for the test:

    package org.apache.geronimo.microprofile.metrics.common;
    
    import static java.util.Collections.singletonMap;
    import static org.junit.Assert.assertEquals;
    
    import javax.ws.rs.core.SecurityContext;
    import javax.ws.rs.core.UriInfo;
    
    import org.apache.geronimo.microprofile.metrics.common.jaxrs.MetricsEndpoints;
    import org.apache.geronimo.microprofile.metrics.common.jaxrs.SecurityValidator;
    import org.apache.geronimo.microprofile.metrics.common.prometheus.PrometheusFormatter;
    import org.eclipse.microprofile.metrics.Gauge;
    import org.junit.Test;
    
    public class MetricsEndpointTest {
        @Test
        public void run() {
            final RegistryImpl registry = new RegistryImpl();
            registry.register("foo", (Gauge<Long>) () -> 1L);
    
            final MetricsEndpoints endpoints = new MetricsEndpoints();
            endpoints.setApplicationRegistry(registry);
            endpoints.setPrometheus(new PrometheusFormatter());
            endpoints.setSecurityValidator(new SecurityValidator() {
                @Override
                public void checkSecurity(final SecurityContext securityContext, final UriInfo uriInfo) {
                    // no-op
                }
            });
            final Object json = endpoints.getJson("application", "foo", null, null);
            assertEquals(singletonMap("foo", 1L), json);
        }
    }

**Comment by rmannibucau** [comment]
Applied, thanks a lot Ivan

**Pull request merged**
