### PR TITLE
reproduce simplified failing TCK test

### PR DESCRIPTION
**Pull request by rotty3000**
I'm having an issue with this TCK test so I replicated it without the container. But I'm not sure what's going wrong. I think the algorithm might be off.

### CODE REVIEW

**Comment by rotty3000** [comment]
I'm not really expecting this for merge. I'm more looking for help to resolve the failing test. Maybe someone can fetch the branch and debug the unit test or something.

**Review by rmannibucau — COMMENTED** [review]
We didnt pick an exponential decay cause it fits only a small part of metrics, maybe thus test assumes it?

**Comment by rotty3000** [comment]
ok right, I think this test is specifically checking that.

**Comment by rotty3000** [comment]
.. wish I had the knowledge to implement that. I think it's the only failing thing in this upgrade :(

**Comment by rmannibucau** [comment]
@rotty3000 hello Raymond, think we fixed that, can you confirm when you have a few sec?

**Pull request closed without merging**
